/**
 * Intelligence Configuration Schema (B12)
 *
 * Tenant-level Machine capabilities configuration.
 */

import { z } from "zod";
import {
  INTEL_DOCUMENT_TYPE,
  RECOMMENDATION_TYPE,
  FORECAST_GRANULARITY,
} from "./constants";

// ============================================================================
// Anomaly Detection Config Schema
// ============================================================================

export const anomalyDetectionConfigSchema = z.object({
  enabled: z.boolean().default(true),
  sensitivityLevel: z.enum(["low", "medium", "high"]).default("medium"),
  enabledDomains: z
    .array(z.string())
    .default(["sales", "purchase", "inventory", "accounting"]),
  notifyCritical: z.boolean().default(true),
  notifyWarning: z.boolean().default(false),
});

export type AnomalyDetectionConfig = z.infer<typeof anomalyDetectionConfigSchema>;

// ============================================================================
// Forecasting Config Schema
// ============================================================================

export const forecastingConfigSchema = z.object({
  enabled: z.boolean().default(true),
  defaultHorizon: z.number().int().positive().default(12),
  defaultGranularity: z.enum(FORECAST_GRANULARITY).default("monthly"),
  autoGenerateDemandForecasts: z.boolean().default(false),
  autoGenerateCashFlowForecasts: z.boolean().default(false),
});

export type ForecastingConfig = z.infer<typeof forecastingConfigSchema>;

// ============================================================================
// Document Config Schema
// ============================================================================

export const documentConfigSchema = z.object({
  enabled: z.boolean().default(true),
  autoClassify: z.boolean().default(true),
  autoExtract: z.boolean().default(true),
  minimumConfidence: z.number().min(0).max(1).default(0.7),
  supportedTypes: z
    .array(z.enum(INTEL_DOCUMENT_TYPE))
    .default(["invoice", "purchase_order", "receipt"]),
});

export type DocumentConfig = z.infer<typeof documentConfigSchema>;

// ============================================================================
// Recommendation Config Schema
// ============================================================================

export const recommendationConfigSchema = z.object({
  enabled: z.boolean().default(true),
  enabledTypes: z
    .array(z.enum(RECOMMENDATION_TYPE))
    .default(["reorder", "pricing"]),
  autoApplyLowRisk: z.boolean().default(false),
  minimumConfidence: z.number().min(0).max(1).default(0.8),
});

export type RecommendationConfig = z.infer<typeof recommendationConfigSchema>;

// ============================================================================
// Assistant Config Schema
// ============================================================================

export const assistantConfigSchema = z.object({
  enabled: z.boolean().default(true),
  allowedDomains: z.array(z.string()).default(["all"]),
  maxTokensPerQuery: z.number().int().positive().default(2000),
  enableActionExecution: z.boolean().default(false),
});

export type AssistantConfig = z.infer<typeof assistantConfigSchema>;

// ============================================================================
// Intelligence Features Schema
// ============================================================================

export const intelligenceFeaturesSchema = z.object({
  anomalyDetection: z.boolean().default(true),
  forecasting: z.boolean().default(true),
  documentAI: z.boolean().default(true),
  recommendations: z.boolean().default(true),
  smartAssistant: z.boolean().default(true),
});

export type IntelligenceFeatures = z.infer<typeof intelligenceFeaturesSchema>;

// ============================================================================
// Intelligence Config Schema
// ============================================================================

export const intelligenceConfigSchema = z.object({
  tenantId: z.uuid(),

  // Feature toggles
  features: intelligenceFeaturesSchema,

  // Detailed settings
  anomalyDetection: anomalyDetectionConfigSchema,
  forecasting: forecastingConfigSchema,
  documentAI: documentConfigSchema,
  recommendations: recommendationConfigSchema,
  assistant: assistantConfigSchema,

  updatedAt: z.string().datetime(),
  updatedBy: z.uuid(),
});

export type IntelligenceConfig = z.infer<typeof intelligenceConfigSchema>;
