# Migrating to Drizzle Declarative RLS - NexusCanon AXIS

**Status:** ⚠️ Currently using SQL-based RLS  
**Target:** Drizzle `crudPolicy` for maintainability  
**Impact:** Zero runtime changes, easier maintenance

---

## 📊 Current vs Target State

### Current Implementation (SQL-based)

```sql
-- scripts/enable-rls.ts generates this:
ALTER TABLE requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can access own tenant data"
  ON requests
  FOR ALL
  TO authenticated
  USING (tenant_id = auth.user_tenant_id())
  WITH CHECK (tenant_id = auth.user_tenant_id());
```

**Issues:**
- ❌ RLS policies separate from schema definition
- ❌ Manual SQL scripts required
- ❌ Hard to review (SQL in separate files)
- ❌ Easy to forget when adding new tables
- ❌ No type safety

### Target Implementation (Drizzle Declarative)

```typescript
// packages/db/src/schema.ts
import { crudPolicy, authenticatedRole } from 'drizzle-orm/neon';
import { sql } from 'drizzle-orm';

export const requests = pgTable("requests", {
  // ... columns ...
}, (table) => ({
  // Indexes
  tenantIdIdx: index("requests_tenant_id_idx").on(table.tenantId),
  
  // RLS Policies (NEW!)
  tenantPolicy: crudPolicy({
    role: authenticatedRole,
    read: sql`(tenant_id = auth.user_tenant_id())`,
    modify: sql`(tenant_id = auth.user_tenant_id())`,
  }),
}));
```

**Benefits:**
- ✅ RLS policies in schema (single source of truth)
- ✅ Auto-generated by Drizzle migrations
- ✅ Easy to review (TypeScript in schema file)
- ✅ Type-safe
- ✅ Can't forget (part of table definition)

---

## 🚀 Migration Path

### Step 1: Install Drizzle RLS Support

```bash
# Ensure you have latest Drizzle with RLS support
pnpm add drizzle-orm@latest drizzle-kit@latest
```

**Check version:**
```bash
pnpm list drizzle-orm
# Should be >= 0.29.0 (RLS support added)
```

### Step 2: Update Schema with `crudPolicy`

<function_calls>
<invoke name="write">
<parameter name="contents">// packages/db/src/schema-with-rls.ts
// EXAMPLE: Drizzle schema with declarative RLS policies
//
// This shows how to migrate your current SQL-based RLS to Drizzle's crudPolicy.
// Once migrated, RLS policies are declared in schema and auto-generated by migrations.

import { 
  pgTable, 
  text, 
  timestamp, 
  uuid, 
  bigint, 
  integer, 
  boolean, 
  index,
  pgPolicy,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { crudPolicy, authenticatedRole, authUid } from "drizzle-orm/neon";

// ============================================================================
// Common Columns
// ============================================================================

export const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
};

// ============================================================================
// Helper: Tenant-scoped RLS check
// ============================================================================

// This SQL expression is reused across all tenant-scoped tables
const tenantScope = (tenantIdColumn: any) => 
  sql`(${tenantIdColumn} = auth.user_tenant_id())`;

// ============================================================================
// Tenants Table (No RLS - self-referential)
// ============================================================================

export const tenants = pgTable("tenants", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  slug: text("slug").notNull().unique(),
  ...timestamps,
});

// ============================================================================
// Users Table (Multi-tenant with RLS)
// ============================================================================

export const users = pgTable("users", {
  id: uuid("id").primaryKey().defaultRandom(),
  tenantId: uuid("tenant_id")
    .notNull()
    .references(() => tenants.id),
  email: text("email").notNull(),
  name: text("name"),
  ...timestamps,
}, (table) => ({
  // Indexes
  tenantIdIdx: index("users_tenant_id_idx").on(table.tenantId),
  
  // RLS Policy: Users can only access users in their tenant
  tenantPolicy: crudPolicy({
    role: authenticatedRole,
    read: tenantScope(table.tenantId),
    modify: tenantScope(table.tenantId),
  }),
}));

// ============================================================================
// Requests Table (Multi-tenant with RLS)
// ============================================================================

export const requests = pgTable("requests", {
  id: uuid("id").primaryKey().defaultRandom(),
  tenantId: uuid("tenant_id")
    .notNull()
    .references(() => tenants.id),
  requesterId: uuid("requester_id").notNull(),
  status: text("status").notNull(),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
  approvedBy: uuid("approved_by"),
  evidenceRequiredForApproval: boolean("evidence_required_for_approval")
    .notNull()
    .default(false),
  evidenceTtlSeconds: integer("evidence_ttl_seconds"),
  ...timestamps,
}, (table) => ({
  // Indexes
  tenantIdIdx: index("requests_tenant_id_idx").on(table.tenantId),
  statusIdx: index("requests_status_idx").on(table.status),
  tenantCreatedIdx: index("requests_tenant_created_idx")
    .on(table.tenantId, table.createdAt.desc()),
  requesterIdx: index("requests_requester_id_idx").on(table.requesterId),
  
  // RLS Policy: Tenant-scoped access
  tenantPolicy: crudPolicy({
    role: authenticatedRole,
    read: tenantScope(table.tenantId),
    modify: tenantScope(table.tenantId),
  }),
}));

// ============================================================================
// Audit Logs (Multi-tenant with RLS)
// ============================================================================

export const auditLogs = pgTable("audit_logs", {
  id: uuid("id").primaryKey().defaultRandom(),
  tenantId: uuid("tenant_id").references(() => tenants.id),
  actorId: uuid("actor_id"),
  traceId: text("trace_id"),
  eventName: text("event_name").notNull(),
  eventData: text("event_data"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
}, (table) => ({
  // Indexes
  tenantIdIdx: index("audit_logs_tenant_id_idx").on(table.tenantId),
  tenantCreatedIdx: index("audit_logs_tenant_created_idx")
    .on(table.tenantId, table.createdAt.desc()),
  
  // RLS Policy: Tenant-scoped access
  tenantPolicy: crudPolicy({
    role: authenticatedRole,
    read: tenantScope(table.tenantId),
    modify: tenantScope(table.tenantId),
  }),
}));

// ============================================================================
// Evidence Files (Multi-tenant with RLS + Status-based access)
// ============================================================================

export const evidenceFiles = pgTable("evidence_files", {
  id: uuid("id").primaryKey().defaultRandom(),
  tenantId: uuid("tenant_id")
    .notNull()
    .references(() => tenants.id),
  uploadedBy: uuid("uploaded_by").notNull(),
  originalName: text("original_name").notNull(),
  mimeType: text("mime_type").notNull(),
  sizeBytes: bigint("size_bytes", { mode: "number" }).notNull(),
  sha256: text("sha256"),
  r2Key: text("r2_key").notNull().unique(),
  sourceR2Key: text("source_r2_key"),
  viewR2Key: text("view_r2_key"),
  status: text("status").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
}, (table) => ({
  // Indexes
  tenantIdIdx: index("evidence_files_tenant_id_idx").on(table.tenantId),
  statusIdx: index("evidence_files_status_idx").on(table.status),
  uploadedByIdx: index("evidence_files_uploaded_by_idx").on(table.uploadedBy),
  
  // RLS Policy: Tenant-scoped access
  tenantPolicy: crudPolicy({
    role: authenticatedRole,
    read: tenantScope(table.tenantId),
    modify: tenantScope(table.tenantId),
  }),
  
  // Advanced Policy: Users can only delete their own uploads
  deleteOwnPolicy: pgPolicy("delete_own_uploads", {
    for: "delete",
    to: authenticatedRole,
    using: sql`(${table.uploadedBy} = auth.user_id())`,
  }),
}));

// ============================================================================
// Request Templates (Multi-tenant with RLS)
// ============================================================================

export const requestTemplates = pgTable("request_templates", {
  id: uuid("id").primaryKey().defaultRandom(),
  tenantId: uuid("tenant_id")
    .notNull()
    .references(() => tenants.id),
  name: text("name").notNull(),
  description: text("description"),
  evidenceRequiredForApproval: boolean("evidence_required_for_approval")
    .notNull()
    .default(false),
  evidenceTtlSeconds: integer("evidence_ttl_seconds"),
  ...timestamps,
}, (table) => ({
  // Indexes
  tenantIdIdx: index("request_templates_tenant_id_idx").on(table.tenantId),
  
  // RLS Policy: Tenant-scoped access
  tenantPolicy: crudPolicy({
    role: authenticatedRole,
    read: tenantScope(table.tenantId),
    modify: tenantScope(table.tenantId),
  }),
}));

// ============================================================================
// Request Evidence Links (Multi-tenant with RLS)
// ============================================================================

export const requestEvidenceLinks = pgTable("request_evidence_links", {
  id: uuid("id").primaryKey().defaultRandom(),
  tenantId: uuid("tenant_id")
    .notNull()
    .references(() => tenants.id),
  requestId: uuid("request_id")
    .notNull()
    .references(() => requests.id),
  evidenceFileId: uuid("evidence_file_id")
    .notNull()
    .references(() => evidenceFiles.id),
  linkedBy: uuid("linked_by").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
}, (table) => ({
  // Indexes
  tenantIdIdx: index("request_evidence_links_tenant_id_idx").on(table.tenantId),
  requestIdIdx: index("request_evidence_links_request_id_idx").on(table.requestId),
  evidenceFileIdIdx: index("request_evidence_links_evidence_file_id_idx")
    .on(table.evidenceFileId),
  
  // RLS Policy: Tenant-scoped access
  tenantPolicy: crudPolicy({
    role: authenticatedRole,
    read: tenantScope(table.tenantId),
    modify: tenantScope(table.tenantId),
  }),
}));

// ============================================================================
// Type Exports
// ============================================================================

export type Tenant = typeof tenants.$inferSelect;
export type NewTenant = typeof tenants.$inferInsert;

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;

export type Request = typeof requests.$inferSelect;
export type NewRequest = typeof requests.$inferInsert;

export type AuditLog = typeof auditLogs.$inferSelect;
export type NewAuditLog = typeof auditLogs.$inferInsert;

export type EvidenceFile = typeof evidenceFiles.$inferSelect;
export type NewEvidenceFile = typeof evidenceFiles.$inferInsert;

export type RequestTemplate = typeof requestTemplates.$inferSelect;
export type NewRequestTemplate = typeof requestTemplates.$inferInsert;

export type RequestEvidenceLink = typeof requestEvidenceLinks.$inferSelect;
export type NewRequestEvidenceLink = typeof requestEvidenceLinks.$inferInsert;
