import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/lib/utils.ts",
    "src/components/button.tsx",
    "src/components/card.tsx",
    "src/components/input.tsx",
    "src/components/label.tsx",
    "src/components/badge.tsx",
    "src/components/separator.tsx",
    "src/components/skeleton.tsx",
    "src/components/spinner.tsx",
    "src/components/avatar.tsx",
    "src/components/tooltip.tsx",
    "src/components/dialog.tsx",
    "src/components/dropdown-menu.tsx",
    "src/components/select.tsx",
    "src/components/checkbox.tsx",
    "src/components/switch.tsx",
    "src/components/tabs.tsx",
    "src/components/scroll-area.tsx",
    "src/components/table.tsx",
    "src/components/form.tsx",
    "src/components/alert.tsx",
    "src/components/progress.tsx",
    "src/components/accordion.tsx",
  ],
  format: ["esm"],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  external: ["react", "react-dom"],
  treeshake: true,
  minify: false,
});
